#!/usr/bin/with-contenv sh

UMASK_SET=${UMASK_SET:-022}
WEBUI_PORT=${WEBUI_PORT:-8080}

umask "$UMASK_SET"

if [ ! -f /config/qBittorrent.conf ]; then
	cp /defaults/qBittorrent.conf /config/qBittorrent.conf
fi

exec \
	s6-setuidgid user qbittorrent-nox --webui-port="${WEBUI_PORT}"