#!/usr/bin/with-contenv sh

# make our folders
mkdir -p \
	/config/qBittorrent \
	/config/data

# copy config
[[ ! -e /config/qBittorrent/qBittorrent.conf ]] && \
	cp /defaults/qBittorrent.conf /config/qBittorrent/qBittorrent.conf

# chown download directory if currently set to root
if [[ "$(stat -c '%U' /downloads)" != "user" ]]; then
	chown -R user:user /downloads
fi

# permissions
chown -R user:user \
	/config